Precomputations
tlspuffin/tlspuffin pull request #333
Opened 2024-09-17 19:10 UTC by aeyno

2024-10-09 11:11 UTC, michaelmera requested changes
I marked some small mistakes that need to be fixed before merging this PR, but it's mainly the resultant of the big merge/rebase you had to do. I'm okay with the conceptual changes that this PR implements.

Also, the first commit of the PR should be removed: it's reverted by a following commit and is not part of this PR.

2024-10-09 11:11 UTC, michaelmera commented on puffin/src/trace.rs
> +            .filter(|raw| (query.source == None || query.source.as_ref().unwrap() == &raw.source))
Keep `.is_none()`. It's [best practice](https://rust-lang.github.io/rust-clippy/master/index.html#/partialeq_to_none).

2024-10-09 17:36 UTC, aeyno commented on puffin/src/algebra/atoms.rs
> +    fn fmt(&self, f: &mut Formatter<'_>) -> fmt::Result {
Done, but why do we need to use a path to use Formatter instead of just importing it ?

2024-10-15 14:54 UTC, LCBH approved these changes
LGTM

2024-10-15 17:32 UTC, michaelmera approved these changes

2024-10-15 17:46 UTC, merged