[WIP] Differential fuzzing
tlspuffin/tlspuffin pull request #345
Opened 2024-10-31 11:56 UTC by aeyno

2026-02-18 14:05 UTC, nataelbaffou reviewed
# Fixes
- sshpuffin/src/ssh/seeds.rs:183 -> missing 3rd parameter in execute method
  - We don't run the sshpuffin tests in the CI ?

# Other notes
- Should some tests be added ?
- Lots of scripts in evaluation-ddyf, maybe add an explanation at the beginning of each one to explain a bit more what it does or an MD file to put all those explanations ?
- "Triage" does exist in english but mostly mean something different [cambridge](https://dictionary.cambridge.org/fr/dictionnaire/anglais/triage). We can find still find it in software development ([wiki](https://en.wikipedia.org/wiki/Software_bug#Management)) but more about prioritising than sorting. Maybe using "Sorting" would make more sense ?

Maybe I am being too nitpicky, the work is really great and the code clean.

2026-02-18 14:05 UTC, nataelbaffou commented on puffin/src/claims.rs
> +        let blacklist = <C::PT as ProtocolTypes>::differential_fuzzing_claims_blacklist();
Maybe add some comments to explain the logic behind the processing of the claims, like explained if the conf (dedupping, ordering, ...)

2026-02-18 14:05 UTC, nataelbaffou commented on puffin/src/cli.rs
> +                .arg(arg!(-p --differential_post_computations "Evaluate the post execution terms ued in differential fuzzing").value_parser(value_parser!(bool)))
typo
```suggestion
                .arg(arg!(-p --differential_post_computations "Evaluate the post execution terms used in differential fuzzing").value_parser(value_parser!(bool)))
```

2026-02-18 14:05 UTC, nataelbaffou commented on puffin/src/differential.rs
> +/// A difference between to exection in differential fuzzing
typo

2026-02-18 14:05 UTC, nataelbaffou commented on puffin/src/cli.rs
> -    if is_experiment {
is_experiment variable is not longer is use, you can remove it and all respective returned values (true, false) from the if-else statement

2026-02-18 14:05 UTC, nataelbaffou commented on puffin/src/protocol.rs
> +}
It seems unused as the "boxed" method was already is "EvaluatedTerm" trait. Did you want to replace it ?

2026-02-18 14:05 UTC, nataelbaffou commented on puffin/src/trace.rs
> +                // )
@LCBH should we add an issue or should it be fixed in the "update_rustc_cargo_versions" branch ?

2026-02-18 14:05 UTC, nataelbaffou commented on puffin/src/trace.rs
> +            // )
(COPY) @LCBH should we add an issue or should it be fixed in the "update_rustc_cargo_versions" branch ?

2026-02-18 14:05 UTC, nataelbaffou commented on sshpuffin/Cargo.toml
> +comparable = { workspace = true }
You need the "derive" feature and you get it from the puffin/Cargo.toml. But is it a better practive to also include it here ?

2026-02-18 14:05 UTC, nataelbaffou commented on tlspuffin/Cargo.toml
> +comparable = { workspace = true }
(COPY) You need the "derive" feature and you get it from the puffin/Cargo.toml. But is it a better practive to also include it here ?

2026-02-24 12:19 UTC, nataelbaffou commented on puffin/src/cli.rs
> +            Command::new("differential")
Maybe change the command to "quick-differential" for consistency

2026-02-24 12:21 UTC, nataelbaffou commented on puffin/src/cli.rs
Add "differential" or "quick-differential" here for consistency

2026-03-02 15:18 UTC, aeyno commented on puffin/src/cli.rs
> +            Command::new("differential")
Technically it is not an experiment (objectives are stored in the `objectives` folder) and you can't provide any experiment title like with quick-experiment. This command is closer to running a differential fuzzing campaign without using the fuzzer without any command.

2026-03-03 14:21 UTC, aeyno commented on puffin/src/differential.rs
> +/// A difference between to exection in differential fuzzing
Done

2026-03-03 14:21 UTC, aeyno commented on puffin/src/cli.rs
> +                .arg(arg!(-p --differential_post_computations "Evaluate the post execution terms ued in differential fuzzing").value_parser(value_parser!(bool)))
Done

2026-03-03 14:21 UTC, aeyno commented on puffin/src/protocol.rs
> +}
Done

2026-03-03 14:22 UTC, aeyno commented on puffin/src/trace.rs
> +            // )
As discussed IRL, we will do another PR to replace the code when the rust version will be updated

2026-03-03 14:22 UTC, aeyno commented on tlspuffin/Cargo.toml
> +comparable = { workspace = true }
Done

2026-03-03 14:44 UTC, aeyno commented on sshpuffin/Cargo.toml
> +comparable = { workspace = true }
done

2026-03-03 14:44 UTC, aeyno commented on puffin/src/trace.rs
> +                // )
duplicate

2026-03-03 14:44 UTC, aeyno commented on puffin/src/cli.rs
duplicate

2026-03-04 10:41 UTC, aeyno commented on puffin/src/cli.rs
> -    if is_experiment {
done

2026-03-04 11:16 UTC, aeyno commented on puffin/src/claims.rs
> +        let blacklist = <C::PT as ProtocolTypes>::differential_fuzzing_claims_blacklist();
done

2026-03-11 16:11 UTC, LCBH requested changes

2026-03-11 16:11 UTC, LCBH commented on puffin/src/fuzzer/harness.rs
> +    let agent = input.descriptors[0].name;
Protect this in case descriptors is empty.

2026-03-11 16:11 UTC, LCBH commented on puffin/src/fuzzer/harness.rs
> +        Spawner::new(put_registry.clone()).with_mapping(&[(agent, put_descriptor.clone())]),
Why don't we map all agents from the trace? Here, we only do so for the first in the list.

2026-03-11 16:11 UTC, LCBH commented on puffin/src/fuzzer/harness.rs
> +    let agent = input.descriptors[0].name;
Same here

2026-03-11 16:11 UTC, LCBH commented on puffin/src/protocol.rs
> +    /// that unifomize the behavior of the PUTs
typo

2026-03-11 16:11 UTC, LCBH commented on puffin/src/protocol.rs
> +    /// eg. decryption recipes
typo

2026-03-11 16:11 UTC, LCBH commented on puffin/src/protocol.rs
> +                        todo!("Comparable for {}", other.type_name());
Do we really want to panic here? Don't we want log::err instead?

2026-03-11 16:11 UTC, LCBH commented on puffin/src/protocol.rs
> +    /// Check wether a difference should be kept
typo

2026-03-11 16:11 UTC, LCBH commented on puffin/Cargo.toml
> +ddyf-disable-status = []
Add a one-liner comment to explain this is for ablation study

2026-03-11 16:11 UTC, LCBH commented on puffin/src/claims.rs
> +            for i in 0..usize::max(s.len(), o.len()) {
Can't we simply apply Comparable on the two lists? (hmm not sure actually since we treat differently the case different content from the case missing content...)

2026-03-11 16:11 UTC, LCBH commented on puffin/src/codec.rs
> +        false => std::cmp::Ordering::Greater,
Why no Equal case? Seems to violate the Ord contract

2026-03-11 16:11 UTC, LCBH commented on puffin/src/put_registry.rs
> +        PutDescriptor::new(self.default_put_name(), PutOptions::empty())
Use `self.default_put.options` rather. than `PutOptions::empty()`?!

2026-03-11 16:11 UTC, LCBH commented on puffin/src/differential.rs
> +    /// The two knowledges have the same type but there internal values are different
typo

2026-03-11 16:11 UTC, LCBH commented on puffin/src/cli.rs
> -        config.is_experiment = is_experiment;
We never set config.is_experiment to true now, which is needed for correct logging (see where it was used). Was this intentional?

2026-03-11 16:11 UTC, LCBH commented on puffin/src/cli.rs
> +                experiment_path
Since the two branches have the same code, merge them.

2026-03-11 16:11 UTC, LCBH commented on puffin/src/cli.rs
> +        let agent = trace.descriptors[0].name;
Better deal with cases where the list is empty.

2026-03-11 16:11 UTC, LCBH commented on puffin/src/cli.rs
> +                .with_mapping(&[(agent, PutDescriptor::new(first_put, PutOptions::empty()))]),
Why only the first agent of the trace is set?

2026-03-11 16:11 UTC, LCBH commented on puffin/src/cli.rs
> +        return match runner.execute(trace, &mut 0, false) {
Is the `false` intended here?

2026-03-11 16:11 UTC, LCBH commented on puffin/src/execution.rs
> +            check_security_violation,
Wouldn't be cleaner to includer this into ConfigTrace instead?

2026-03-11 16:11 UTC, LCBH commented on puffin/src/execution.rs
> +            check_security_violation,
Hmm, would need to add this parameter to `execute` as well then. To be discussed.

2026-03-11 16:11 UTC, LCBH commented on puffin/src/execution.rs
> +    /// Execute `trace` on the two PUT of `self`, return `Ok` if both execution exhibit no
typos

2026-03-11 16:11 UTC, LCBH commented on puffin/src/execution.rs
> +        let mut diff = match (&first_trace_status, &second_trace_status) {
Is it intended to check this only if there is no status difference? I feel that security claim violations are "more severe" and less prone to false positives....

2026-03-11 16:11 UTC, LCBH commented on puffin/src/execution.rs
> +        Ok(first_ctx)
You never want to access both contexts? I reckon that you already checked that they are both "the same" but this still allows some differences that are filtered out.

2026-03-11 16:11 UTC, LCBH commented on puffin/src/execution.rs
> +                with_bit_level: false,
Why not letting the user choose this. It would be nice to do diff fuzzing with havoc mutations enabled.

2026-03-11 16:11 UTC, LCBH commented on puffin/src/execution.rs
> +                with_bit_level: false,
See how it is done for the other implem of `execute`.

2026-03-11 16:11 UTC, LCBH commented on puffin/src/trace.rs
> +/// Should a specific knowledge be filtered out
"should be kept (not filtered out)" right?

2026-03-11 16:11 UTC, LCBH commented on puffin/src/trace.rs
> +        if !list.iter().any(|x| x == &knowledge.data.type_id()) {
Hmmm, I am confused. If it is in the white list --> it is always kept. If not, it is kept only if it is not in the blacklist. No?

2026-03-11 16:11 UTC, LCBH commented on puffin/src/trace.rs
> +                // )
This will be doable now.

2026-03-11 16:11 UTC, LCBH commented on puffin/src/trace.rs
> +                        .filter(|c| c.get_step() == Some(StepNumber::new(trace_number, idx)))
This whole block and this filtering needs documentation

2026-03-11 16:11 UTC, LCBH commented on puffin/src/trace.rs
> +                        .filter(|c| c.get_step() == Some(StepNumber::new(trace_number, idx)))
Actually yhe whole function would need better documentation.

2026-03-11 16:11 UTC, LCBH commented on puffin/src/trace.rs
>              prior_traces: Vec::new(),
Why not just putting here the prior traces from the trace?

2026-03-11 16:11 UTC, LCBH commented on puffin/src/protocol.rs
> +macro_rules! dummy_compare {
Is this used somewhere (I cannot find any occurence)

2026-03-11 16:11 UTC, LCBH commented on puffin/src/protocol.rs
> +            fn find_differences(
Wrong function signature!

2026-03-11 16:11 UTC, LCBH commented on puffin/src/cli.rs
> +        let agent = trace.descriptors[0].name;
Another occurence of this in this file

2026-03-11 16:11 UTC, LCBH commented on puffin/src/trace.rs
> +            .map(|(idx, (x, y))| {
Rather uses `.for_each()`?

2026-03-12 16:47 UTC, nataelbaffou commented on puffin/src/cli.rs
> -        config.corpus_dir = base_directory.join("corpus");
Il faut garder ces configs pour tout avoir dans l'experiment en cours et non à la racine du projet

2026-03-16 16:55 UTC, LCBH requested changes

2026-03-16 16:55 UTC, LCBH commented on tlspuffin/harness/openssl/src/put.c
> -        if (!allow_would_block)
This followed quite a lot of discussions and was not trivial at all. It would be nice to document a bit the rationale. Ideally, add a documentation at the start of the case distinctions with the rationale.

2026-03-16 16:55 UTC, LCBH commented on tlspuffin/src/tls/rustls/msgs/handshake.rs
> +    #[comparable_ignore]
[Compare] Why ignoring this? Is this randomized? Different for different PUTs?

2026-03-16 16:55 UTC, LCBH commented on tlspuffin/src/tls/rustls/msgs/handshake.rs
> +    #[comparable_ignore]
[Compare] Just for the discussion: do we agree that we could theoretically make sure to configure agents so that this field should be aligned? (If yes, just add a comment saying this)

2026-03-16 16:55 UTC, LCBH commented on tlspuffin/src/tls/rustls/msgs/handshake.rs
> +    #[comparable_ignore]
[Compare] Why ignoring this? Is this randomized? Different for different PUTs?

2026-03-16 16:55 UTC, LCBH commented on tlspuffin/src/tls/rustls/msgs/handshake.rs
> +    ECPointFormats(#[comparable_ignore] ECPointFormatList),
[Compare] Just for the discussion: do we agree that we could theoretically make sure to configure agents so that this field should be aligned? (If yes, just add a comment saying this)

2026-03-16 16:55 UTC, LCBH commented on tlspuffin/src/tls/rustls/msgs/handshake.rs
> +    ECPointFormats(#[comparable_ignore] ECPointFormatList),
[Compare] Just for the discussion: do we agree that we could theoretically make sure to configure agents so that this field should be aligned? (If yes, just add a comment saying this)

2026-03-16 16:55 UTC, LCBH commented on tlspuffin/src/tls/rustls/msgs/handshake.rs
> +        let sorted_cipher_suites = |x: &Self| -> std::collections::HashMap<CipherSuite, ()> { let ciphers : std::collections::HashMap<CipherSuite, ()>= x.cipher_suites.0.clone().into_iter().map(|c| (
[compare] why removing duplicates? Don't we want to compare as multisets? (as for extensions)

2026-03-16 16:55 UTC, LCBH commented on tlspuffin/src/tls/rustls/msgs/handshake.rs
>      pub curve_params: ECParameters,
[Compare] Just for the discussion: do we agree that we could theoretically make sure to configure agents so that this field should be aligned? (If yes, just add a comment saying this)

2026-03-16 16:55 UTC, LCBH commented on tlspuffin/src/tls/rustls/msgs/handshake.rs
> +    #[comparable_ignore]
[Compare] Why ignoring this? Is this randomized? Different for different PUTs?

2026-03-16 16:55 UTC, LCBH commented on tlspuffin/src/tls/rustls/msgs/message.rs
> +impl PartialEq for MessagePayload {
Why do we need a custom PartialEq implem here?

2026-03-16 16:55 UTC, LCBH commented on tlspuffin/src/tls/rustls/hash_hs.rs
> +    #[comparable_ignore]
[Compare] Wait: why don't we have to ignore the other fields (like `override_buffer`)?

2026-03-16 16:55 UTC, LCBH commented on tlspuffin/src/tls/fn_transcript.rs
> +pub fn fn_finished_get_cipher(claim: &Finished) -> Result<CipherSuite, FnError> {
Please add somewhere that these function symbols are never meant to be attacker symbols (from the signature). We should ideally avoid using `fn_XX` for such functions.

2026-03-16 16:55 UTC, LCBH commented on tlspuffin/src/tls/fn_transcript.rs
> +    for (idx, v) in claim.client_random.iter().enumerate() {
No better way to copy a SmallVec?

2026-03-16 16:55 UTC, LCBH commented on tlspuffin/src/tls/fn_transcript.rs
> +    for (idx, v) in claim.server_random.iter().enumerate() {
No better way to copy a SmallVec?

2026-03-16 16:55 UTC, LCBH commented on tlspuffin/src/tls/fn_utils.rs
> +pub fn fn_decrypt_handshake_flight_with_secret(
Add a Rust doc

2026-03-16 16:59 UTC, LCBH requested changes

2026-03-16 16:59 UTC, LCBH commented on tlspuffin/src/claims.rs
> +pub struct TranscriptPartialClientHello(#[comparable_ignore] pub TlsTranscript);
[Compare] Why ignoring this? Shouldn't we compare the length at least? (in TlsTranscript) --> same for other structs in this file

2026-03-16 16:59 UTC, LCBH commented on tlspuffin/src/claims.rs
> +    #[comparable_ignore]
[Compare] Why ignoring this? Is this randomized? Different for different PUTs?

2026-03-16 16:59 UTC, LCBH commented on tlspuffin/src/claims.rs
> +    #[comparable_ignore]
[Compare] Why ignoring this? Is this randomized? Different for different PUTs?

2026-03-16 16:59 UTC, LCBH commented on tlspuffin/src/claims.rs
> +    #[comparable_ignore]
[Compare] Why ignoring this? Is this randomized? Different for different PUTs?

2026-03-16 16:59 UTC, LCBH commented on tlspuffin/src/claims.rs
> +    #[comparable_ignore]
[Compare] Why ignoring this? Is this randomized? Different for different PUTs?

2026-03-16 16:59 UTC, LCBH commented on tlspuffin/src/claims.rs
> +    #[comparable_ignore]
[Compare] Why ignoring this? Is it because we already test the claim step anyway? But then we could also compare this field?!

2026-03-17 09:03 UTC, LCBH requested changes

2026-03-17 09:03 UTC, LCBH commented on tlspuffin/src/query.rs
> +    ClientHelloFlight,
Add some documentation: For example, this is supposed to match any flight starting with a client hello

2026-03-17 09:03 UTC, LCBH commented on tlspuffin/src/protocol.rs
> +    fn differential_fuzzing_blacklist() -> Option<Vec<TypeId>> {
Question: None: is this intended? Why did we need a black list then?

2026-03-17 09:03 UTC, LCBH commented on tlspuffin/src/protocol.rs
> +        for agent in agents {
Would be nice to document this

2026-03-17 09:03 UTC, LCBH commented on tlspuffin/src/protocol.rs
> +    fn differential_fuzzing_claims_blacklist() -> Option<Vec<TypeId>> {
[Compare] Why all of these transcripts? Always different?

2026-03-17 09:03 UTC, LCBH commented on tlspuffin/src/protocol.rs
> +    fn differential_fuzzing_uniformise_put_config(mut trace: Trace<Self>) -> Trace<Self> {
Why taking a `mut` on the input? (the signature is weird)

2026-03-17 09:03 UTC, LCBH commented on tlspuffin/src/protocol.rs
> +        for agent in trace.descriptors.iter_mut() {
Document somewhere (ideally on the official doc) for which vendors this works.

2026-03-17 09:03 UTC, LCBH commented on tlspuffin/src/protocol.rs
> +        trace
Is there a way to test if this has worked (when executing the trace? Is set-cipher capable of detecting failures?)

2026-03-17 09:03 UTC, LCBH commented on tlspuffin/src/protocol.rs
> +        for agent in trace.descriptors.iter_mut() {
Also document here why we chose these ciphers.

2026-03-17 09:03 UTC, LCBH commented on tlspuffin/src/protocol.rs
> +            if diff.contains("EncryptedExtensionsChange([Removed(0, Unknown(UnknownExtensionDesc { typ: EllipticCurves }))])") {
This does not resist changes in struct removing or structure modifications. Is there a way to make this test more robust?

2026-03-17 09:03 UTC, LCBH commented on tlspuffin/Cargo.toml
> +ddyf-disable-status = ["puffin/ddyf-disable-status"]
please document

2026-03-17 09:03 UTC, LCBH commented on tools/differential/list_buckets.sh
> +#!/bin/bash
This script needs documentation

2026-03-17 09:03 UTC, LCBH commented on tools/differential/empty_buckets.sh
> +#!/bin/bash
This script needs documentation

2026-03-24 10:01 UTC, aeyno commented on puffin/src/fuzzer/harness.rs
> +    let agent = input.descriptors[0].name;
done

2026-03-24 10:01 UTC, aeyno commented on puffin/src/fuzzer/harness.rs
> +        Spawner::new(put_registry.clone()).with_mapping(&[(agent, put_descriptor.clone())]),
done

2026-03-24 10:01 UTC, aeyno commented on puffin/src/fuzzer/harness.rs
> +    let agent = input.descriptors[0].name;
done

2026-03-24 10:06 UTC, aeyno commented on puffin/src/protocol.rs
> +    /// eg. decryption recipes
done

2026-03-24 10:15 UTC, aeyno commented on puffin/src/protocol.rs
> +    /// Check wether a difference should be kept
Done

2026-03-24 10:16 UTC, aeyno commented on puffin/Cargo.toml
> +ddyf-disable-status = []
Done

2026-03-24 10:25 UTC, aeyno commented on puffin/src/codec.rs
> +        false => std::cmp::Ordering::Greater,
Changed to support equal case

2026-03-24 10:46 UTC, aeyno commented on puffin/src/differential.rs
> +    /// The two knowledges have the same type but there internal values are different
done

2026-03-26 08:58 UTC, aeyno commented on puffin/src/codec.rs
> +    }
done

2026-03-26 09:00 UTC, aeyno commented on tlspuffin/Cargo.toml
> +ddyf-disable-status = ["puffin/ddyf-disable-status"]
done

2026-03-26 09:02 UTC, aeyno commented on tlspuffin/src/protocol.rs
> +    fn differential_fuzzing_uniformise_put_config(mut trace: Trace<Self>) -> Trace<Self> {
done

2026-03-26 09:08 UTC, aeyno commented on puffin/src/put_registry.rs
> +        PutDescriptor::new(self.default_put_name(), PutOptions::empty())
done

2026-03-26 15:09 UTC, aeyno commented on puffin/src/protocol.rs
> +                        todo!("Comparable for {}", other.type_name());
This macro was not used anymore so I removed it

2026-03-26 15:14 UTC, aeyno commented on puffin/src/cli.rs
> +        let agent = trace.descriptors[0].name;
done

2026-03-26 15:15 UTC, aeyno commented on puffin/src/cli.rs
> +                .with_mapping(&[(agent, PutDescriptor::new(first_put, PutOptions::empty()))]),
done

2026-03-26 15:31 UTC, aeyno commented on puffin/src/cli.rs
> +                experiment_path
done

2026-03-26 15:36 UTC, aeyno commented on puffin/src/execution.rs
> +    /// Execute `trace` on the two PUT of `self`, return `Ok` if both execution exhibit no
done

2026-03-26 15:40 UTC, aeyno commented on puffin/src/execution.rs
> +        let mut diff = match (&first_trace_status, &second_trace_status) {
We just abort the comparison as soon as we detect a status difference for performance reasons , but this kind of differences should be catched during the trace analysis.

2026-03-26 15:44 UTC, aeyno commented on puffin/src/protocol.rs
> +macro_rules! dummy_compare {
Indeed it was not used anymore so I removed it

2026-03-30 08:48 UTC, aeyno commented on puffin/src/claims.rs
> +            for i in 0..usize::max(s.len(), o.len()) {
We could but this increases the readability of the differences: else we would only have a big data structure with all the differences (inner diff and different types) for all the claims.

2026-03-30 08:50 UTC, aeyno commented on puffin/src/cli.rs
> -        config.is_experiment = is_experiment;
This looks like an error during a rebase. I put it back.

2026-03-30 08:55 UTC, aeyno commented on puffin/src/cli.rs
> +        return match runner.execute(trace, &mut 0, false) {
I added `--enable-security-oracle` flag to enable the security oracle which is disabled by default in differential mode.

2026-03-30 09:11 UTC, aeyno commented on tlspuffin/src/protocol.rs
> +    fn differential_fuzzing_claims_blacklist() -> Option<Vec<TypeId>> {
Yes all transcripts are different since they all depend on CH and SH which contains random values.

2026-03-30 09:18 UTC, aeyno commented on tlspuffin/src/claims.rs
> +    #[comparable_ignore]
It was different for OpenSSL and wolfSSL, but I think you introduced the necessary API to changes sigalgs in [!468](https://github.com/tlspuffin/tlspuffin/pull/468). So this could probably be removed when merged.

2026-03-30 09:30 UTC, aeyno commented on tlspuffin/src/claims.rs
> +    #[comparable_ignore]
list of ciphers are different for TLS 1.2, openssl shows 5 (3 TLS 1.3 and two TLS 1.2) while wolfssl shows only the two TLS 1.2 ciphers. So this is an API difference.

2026-03-30 09:35 UTC, aeyno commented on tlspuffin/src/claims.rs
> +    #[comparable_ignore]
This is ignored because it introduces duplicates Finished claims on some PUTs: ignoring this fields makes the oracle deduplicate all adjacent Finished while not ignoring it causes some PUTs to have this claims multiple times with and without `outbound=true`

2026-03-30 13:33 UTC, aeyno commented on puffin/src/execution.rs
> +        Ok(first_ctx)
Changed to return both

2026-03-30 14:35 UTC, aeyno commented on puffin/src/execution.rs
> +                with_bit_level: false,
Changed.

2026-03-30 14:38 UTC, aeyno commented on puffin/src/trace.rs
> +/// Should a specific knowledge be filtered out
Indeed. Changed.

2026-03-30 14:51 UTC, aeyno commented on puffin/src/trace.rs
> +                        .filter(|c| c.get_step() == Some(StepNumber::new(trace_number, idx)))
Done

2026-03-30 15:05 UTC, aeyno commented on puffin/src/cli.rs
> -        config.corpus_dir = base_directory.join("corpus");
done

2026-03-30 15:08 UTC, aeyno commented on tlspuffin/src/tls/rustls/msgs/handshake.rs
> +    #[comparable_ignore]
Since we already ignore SessionIDs in CH and SH, I removed the ignore here

2026-03-31 08:51 UTC, aeyno commented on tlspuffin/src/tls/rustls/msgs/handshake.rs
> +    #[comparable_ignore]
Yes probably, I added the comment.

2026-03-31 09:28 UTC, aeyno commented on tlspuffin/src/tls/rustls/msgs/handshake.rs
> +    #[comparable_ignore]
I tried to remove the ignores and I don't have differences on the seed so I am not sure why I ignored them

2026-03-31 09:49 UTC, aeyno commented on tlspuffin/src/tls/rustls/msgs/handshake.rs
> +    ECPointFormats(#[comparable_ignore] ECPointFormatList),
Done

2026-03-31 09:51 UTC, aeyno commented on tlspuffin/src/tls/rustls/msgs/handshake.rs
> +    ECPointFormats(#[comparable_ignore] ECPointFormatList),
Done

2026-03-31 13:05 UTC, aeyno commented on puffin/src/trace.rs
> +        if !list.iter().any(|x| x == &knowledge.data.type_id()) {
I don't think that the blacklist is really useful, I will probably remove it

2026-03-31 13:07 UTC, aeyno commented on puffin/src/protocol.rs
> +            fn find_differences(
This macro has been removed

2026-03-31 13:07 UTC, aeyno commented on puffin/src/trace.rs
> +            .map(|(idx, (x, y))| {
Done

2026-03-31 13:22 UTC, aeyno commented on tlspuffin/src/tls/rustls/msgs/handshake.rs
> +        let sorted_cipher_suites = |x: &Self| -> std::collections::HashMap<CipherSuite, ()> { let ciphers : std::collections::HashMap<CipherSuite, ()>= x.cipher_suites.0.clone().into_iter().map(|c| (
Ideed, I changed that

2026-03-31 13:47 UTC, aeyno commented on tlspuffin/src/tls/rustls/msgs/handshake.rs
>      pub curve_params: ECParameters,
Done

2026-03-31 13:50 UTC, aeyno commented on tlspuffin/src/tls/rustls/msgs/message.rs
> +impl PartialEq for MessagePayload {
I think that is to avoid having to derive `PartialEq` on all the underlying types (basically all rustls types)

2026-03-31 13:54 UTC, aeyno commented on tlspuffin/src/tls/rustls/msgs/handshake.rs
> +    #[comparable_ignore]
Yes, the lifetime and ticket payloads are PUT dependant. I don't think it is possible to change this value for OpenSSL

2026-03-31 13:57 UTC, aeyno commented on tlspuffin/src/tls/rustls/hash_hs.rs
> +    #[comparable_ignore]
The reason why this field is ignored is that now `digest::Context` doesn't have to implement Comparable.

2026-03-31 14:00 UTC, aeyno commented on tlspuffin/src/tls/fn_transcript.rs
> +pub fn fn_finished_get_cipher(claim: &Finished) -> Result<CipherSuite, FnError> {
Done

2026-03-31 15:16 UTC, aeyno commented on tlspuffin/src/tls/fn_transcript.rs
> +    for (idx, v) in claim.client_random.iter().enumerate() {
Done.

2026-03-31 15:16 UTC, aeyno commented on tlspuffin/src/tls/fn_transcript.rs
> +    for (idx, v) in claim.server_random.iter().enumerate() {
Done.

2026-03-31 15:20 UTC, aeyno commented on tlspuffin/src/tls/fn_utils.rs
> +pub fn fn_decrypt_handshake_flight_with_secret(
Done.

2026-03-31 15:22 UTC, aeyno commented on puffin/src/trace.rs
>              prior_traces: Vec::new(),
Discussed offline. This requires some changes to the way the knowledges are stored to correctly map them to the correct prior trace. I opened an issue: https://github.com/tlspuffin/tlspuffin/issues/476

2026-04-01 09:01 UTC, aeyno commented on tlspuffin/src/claims.rs
> +    #[comparable_ignore]
We ignore the step number because when a claim is present multiple times at multiple steps we can't deduplicate it if they have different step numbers. So we ignore the step number to focus on the succession of claims rather than when they were emitted.

2026-04-01 09:06 UTC, aeyno commented on tlspuffin/src/claims.rs
> +    #[comparable_ignore]
It was different for OpenSSL and wolfSSL, but I think you introduced the necessary API to changes sigalgs in https://github.com/tlspuffin/tlspuffin/pull/468. So this could probably be removed when merged.

2026-04-01 09:11 UTC, aeyno commented on tlspuffin/src/query.rs
> +    ClientHelloFlight,
Done

2026-04-01 09:12 UTC, aeyno commented on tlspuffin/src/protocol.rs
> +    fn differential_fuzzing_blacklist() -> Option<Vec<TypeId>> {
Blacklist has been removed

2026-04-01 09:14 UTC, aeyno commented on tlspuffin/src/protocol.rs
> +        for agent in agents {
Done.

2026-04-01 11:31 UTC, aeyno commented on tlspuffin/src/protocol.rs
> +        for agent in trace.descriptors.iter_mut() {
Done.

2026-04-01 11:37 UTC, aeyno commented on tlspuffin/src/protocol.rs
> +        trace
set_cipher and set_groups are tested in `tlspuffin/tests/harness.rs`

2026-04-01 11:49 UTC, aeyno commented on tlspuffin/src/protocol.rs
> +            if diff.contains("EncryptedExtensionsChange([Removed(0, Unknown(UnknownExtensionDesc { typ: EllipticCurves }))])") {
I changed that to just searching for a difference containing `"UnknownExtensionDesc { typ: EllipticCurves }"`

2026-04-01 11:52 UTC, aeyno commented on puffin/src/trace.rs
> +use comparable::Comparable;
Done.

2026-04-01 11:55 UTC, aeyno commented on tools/differential/list_buckets.sh
> +    total=$((total+num))
Done.

2026-04-01 11:56 UTC, aeyno commented on docs/docs/guides/getting-started/differential-fuzzing.md
> +Start by importing the necessary elements from `./tool/differential/diff-analyzer.py`
Done

2026-04-01 11:56 UTC, aeyno commented on docs/docs/guides/getting-started/differential-fuzzing.md
> +In order to do differential fuzzing, the protocol fuzzer should be configured to minimize the false positives, i.e. all randomized fields (nonces, random, secrets, hash, ciphertext, etc.) should be a
Done.

2026-04-01 11:57 UTC, aeyno commented on extractable-macro/tests/tests.rs
> +    }
Blacklists have been removed.

2026-04-01 12:13 UTC, aeyno commented on tlspuffin/src/claims.rs
> +pub struct TranscriptPartialClientHello(#[comparable_ignore] pub TlsTranscript);
All transcripts are ignored since their content must be different.

2026-04-01 12:27 UTC, aeyno commented on tools/differential/empty_buckets.sh
> +#!/bin/bash
Done.

2026-04-01 12:27 UTC, aeyno commented on tools/differential/list_buckets.sh
> +#!/bin/bash
Done.

2026-04-01 13:33 UTC, aeyno commented on puffin/src/execution.rs
> +        let mut diff = match (&first_trace_status, &second_trace_status) {
TODO: make a security violation obvious to be sure to correctly triage it

2026-04-02 12:13 UTC, aeyno commented on puffin/src/execution.rs
> +            check_security_violation,
Done.

2026-04-02 13:50 UTC, aeyno commented on puffin/src/execution.rs
> +        let mut diff = match (&first_trace_status, &second_trace_status) {
Done.

2026-04-02 15:10 UTC, aeyno commented on tlspuffin/harness/openssl/src/put.c
> -        if (!allow_would_block)
Done

2026-04-02 15:11 UTC, aeyno commented
@LCBH can you allow merging this PR ?

2026-04-02 16:35 UTC, LCBH approved these changes

2026-04-02 16:41 UTC, merged