Adding OpenSSL 3.2.0 and 3.4.0 PUT presets
tlspuffin/tlspuffin pull request #353
Opened 2024-12-13 13:33 UTC by aeyno

2025-01-13 14:41 UTC, LCBH requested changes
Please make sure the CI runs on those versions as well!

2025-01-15 15:05 UTC, aeyno commented
Done @LCBH

2025-01-15 15:10 UTC, LCBH commented
> Done @LCBH

Seems like some tests are failing.

2025-01-15 15:54 UTC, aeyno commented
Now it's working, there was a problem with the EDGE_MAP_SIZE when using `cputs`

2025-01-22 16:22 UTC, michaelmera approved these changes
LGTM

2025-01-27 14:58 UTC, LCBH commented
LGTM

2025-01-27 14:59 UTC, LCBH approved these changes

2025-01-27 14:59 UTC, merged